# Generated by Django 5.2.6 on 2025-09-09 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("result", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
                ("features", models.JSONField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
