# Generated by Django 5.2.6 on 2025-09-09 05:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scanreport",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Scan Report",
                "verbose_name_plural": "Scan Reports",
            },
        ),
        migrations.AlterField(
            model_name="scanreport",
            name="confidence",
            field=models.FloatField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="scanreport",
            name="result",
            field=models.CharField(
                choices=[("phishing", "Phishing"), ("legitimate", "Legitimate")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scanreport",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="scanreport",
            name="url",
            field=models.URLField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="scanreport",
            index=models.Index(
                fields=["timestamp"], name="scanner_sca_timesta_599e69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanreport",
            index=models.Index(fields=["result"], name="scanner_sca_result_729a16_idx"),
        ),
        migrations.AddIndex(
            model_name="scanreport",
            index=models.Index(
                fields=["confidence"], name="scanner_sca_confide_11910b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanreport",
            index=models.Index(
                fields=["url", "timestamp"], name="scanner_sca_url_f9bb86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanreport",
            index=models.Index(
                fields=["result", "confidence"], name="scanner_sca_result_9df527_idx"
            ),
        ),
    ]
