# Generated by Django 5.2.6 on 2025-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0005_useractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("scan", "URL Scan"),
                    ("signup", "User Registration"),
                    ("profile_view", "Profile View"),
                    ("password_changed", "Password Changed"),
                ],
                max_length=20,
            ),
        ),
    ]
